/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CheckIn;

/**
 *
 * @author Ersalina
 */
public class CheckInUI extends javax.swing.JFrame {

    /**
     * Creates new form CheckInUI
     */
    public CheckInUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        CheckIn = new javax.swing.JLabel();
        NomorKendaraan = new javax.swing.JLabel();
        Lantai = new javax.swing.JLabel();
        NomorLot = new javax.swing.JLabel();
        TextNoKendaraan = new javax.swing.JTextField();
        BoxLantai = new javax.swing.JComboBox<>();
        BoxNomorLot = new javax.swing.JComboBox<>();
        buttonCheckin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CheckIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CheckIn.setText("Check In Parking");

        NomorKendaraan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NomorKendaraan.setText("Nomor Kendaraan :");

        Lantai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lantai.setText("Lantai :");

        NomorLot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NomorLot.setText("Nomor Lot :");

        TextNoKendaraan.setMinimumSize(new java.awt.Dimension(5, 25));
        TextNoKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNoKendaraanActionPerformed(evt);
            }
        });

        BoxLantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lantai 1", "Lantai 2", "Lantai 3" }));
        BoxLantai.setMinimumSize(new java.awt.Dimension(5, 25));
        BoxLantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxLantaiActionPerformed(evt);
            }
        });

        BoxNomorLot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lot 1", "Lot 2", "Lot 3", "Lot 4", "Lot 5", "Lot 6", "Lot 7", "Lot 8", "Lot 9", "Lot 10" }));
        BoxNomorLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNomorLotActionPerformed(evt);
            }
        });

        buttonCheckin.setText("CHECK IN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CheckIn)
                        .addComponent(NomorKendaraan)
                        .addComponent(NomorLot)
                        .addComponent(TextNoKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoxLantai, 0, 216, Short.MAX_VALUE)
                        .addComponent(BoxNomorLot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Lantai))
                .addGap(50, 50, 50)
                .addComponent(buttonCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(NomorKendaraan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lantai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxLantai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NomorLot))
                    .addComponent(buttonCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxNomorLot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNoKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNoKendaraanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextNoKendaraanActionPerformed

    private void BoxLantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxLantaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxLantaiActionPerformed

    private void BoxNomorLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNomorLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNomorLotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckInUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxLantai;
    private javax.swing.JComboBox<String> BoxNomorLot;
    private javax.swing.JLabel CheckIn;
    private javax.swing.JLabel Lantai;
    private javax.swing.JLabel NomorKendaraan;
    private javax.swing.JLabel NomorLot;
    private javax.swing.JTextField TextNoKendaraan;
    private javax.swing.JButton buttonCheckin;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
